var GAME_LEVELS = [
  ["                                                                                            ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                  oo                         ",
   "                                                                                             ",
   "                                                   oo                                        ",
   "                                                   xx      xx                                ",
   "                                    o o      xx                                              ",
   "                                                               o                             ",
   "                                   xxxxx                       o                             ",
   "                                                              xxxxxxxxxxxx                   ",
   "  xx                                        o o               x          x            xx     ",
   "  x                           xxxxx         xxx               x          x             x     ",
   "  x            o                                           xxxx          x         o   x     ",
   "  x          xxxx       xxxx                               x             x         o   x     ",
   "  x  @       x  x                                          x             x         o   x     ",
   "  xxxxxxxxxxxx  xxxxxx                         xxxxxxxxxxxxx             x      xxxxxxxx     ",
   "                     x                         x                         x      x            ",
   "                     x!!!!!!!!!!!!!!!!!!!!!!!!!x                         x!!!!!!x            ",
   "                     x!!!!!!!!!!!!!!!!!!!!!!!!!x                         xxxxxxxx            ",
   "                     xxxxxxxxxxxxxxxxxxxxxxxxxxx                                             ",
   "                                                                                             ",
   "                                                                                             "],
   
  ["                                                                                                       ",
   "                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                            ",
   "                           v      v      v        v       x                                            ",
   "                                                          x                                  xxx       ",
   "                                                          xxxxxxxxxxxxxxxxxxxxxxxxxxxx         x       ",
   "                           o       o       o             o                      o          o   x       ",
   "                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      ",
   "          xxxx                                                                                         ",
   "       o                                                                                               ",
   "      xxx                                                                                              ",
   "                                                                       o                               ",
   "        xxxxxxxxx                                                     o                                ",
   "                 xxxxx                          xxxxxxxxxxx            o                               ",
   "                     x        =        =    o   x         x         xxxxxxxx                           ",
   "                     xxxxxxxxxxxxxxxxxxxxxxxxxxxx         x!!!!!!!!!x                                  ",
   "                                                          xxxxxxxxxxx      xxxxxxxxxxx                 ",
   "                                                                                     x                 ",
   "                                                                                     xxxxxxxx          ",
   "                                                                                                       ",
   "                                                               xxxxx                            oo     ",
   "                                                                                               xxxx    ",
   "                               xx                       xxxxx                  o                  x    ",
   "                                           oo                        xxxxxxxxxx             xxxxxxx    ",
   "                   xxxxxxxxx                                                  x!!!!!!!!!!!!!x          ",
   "                o  x       x            xxxxxxxxxxx                           x!!!!!!!!!!!!!x          ",
   "xx                 x       x!!!!!!!!!!!!x                                     xxxxxxxxxxxxxxx          ",
   "x               o  x       xxxxxxxxxxxxxx                                                              ",
   "x         xxxxxxxxxx                                                                                   ",
   "x @       x                                                                                            ",
   "xxxxxxxxxxx                                                                                           "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   oooo   x       xxx                            ",
   "                                      x   x                 x          x      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x           x                    x!!!x                              ",
   "                                      x   x           x                     xxx                               ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "                                      x   x           x           x!!!x                                       ",
   "                                      x   x    = = = =x     o      xxx       xxx                              ",
   "                                     xx   xx          x                     x!!!x                             ",
   "                              o   o   x   x           x     x                xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                             x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx                                         xxx                      ",
   "  xxx                         x     x     x                                         x!!!x                xxx  ",
   "  x x                         x    xxx    x                                          xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                           xx          x                              x x x                             x  ",
   "  x                                       x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                xxx             o o    x                              x         xxx                     x  ",
   "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
   "  x               oxxxo       x    xxx    x                             x x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @          x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
