var GAME_LEVELS = [


  ["                                                                                            ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                  oo                         ",
   "                                                                                             ",
   "                                                   oo                                        ",
   "                                                   xx      xx                                ",
   "                                    o o      xx                                              ",
   "                                                               o                             ",
   "                                   xxxxx                       o   ppp                       ",
   "                                                              xxxxxxxxxxxx                   ",
   "  xx                                        o o               x          x            xx     ",
   "  x                           xxxxx         xxx               x          x             x     ",
   "  x           oo                                           xxxx          x         o   x     ",
   "  x          xxxx       xxxx                               x             x         o   x     ",
   "  x  @       x  x  pp                                ppp   x             x         o   x     ",
   "  xxxxxxxxxxxx  xxxxxx                         xxxxxxxxxxxxx             x      xxxxxxxx     ",
   "                     x                         x                         x      x            ",
   "                     x!!!!!!!!!!!!!!!!!!!!!!!!!x                         x!!!!!!x            ",
   "                     x!!!!!!!!!!!!!!!!!!!!!!!!!x                         xxxxxxxx            ",
   "                     xxxxxxxxxxxxxxxxxxxxxxxxxxx                                             ",
   "                                                                                             ",
   "                                                                                             "],
   
   
   
  ["                                                                                                      ",
   "                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                           ",
   "                           v      v      v        v       x                                           ",
   "                                                          x                                           ",
   "                                                          x                                           ",
   "                                                          x                                           ",
   "                                                          x                                           ",
   "                                                          xxxxxxxxxxxxxxxxxxxxxxxxxxx                 ",
   "                                                                                                      ",
   "                                                                                               xx     ",
   "                                                                                                x     ",
   "                           o       o       o             o                      o          o    x     ",
   "                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     ",
   "            xxxx                                                                                      ",
   "       o                                                                                              ",
   "     xxxx                                                                                             ",
   "                                                                                                      ",
   "                                                                                                      ",
   "        pppp                                                   xx      o                              ",
   "        xxxxxxxxx          o          o                                o                              ",
   "                 xxxxx                          xxxxxxxxxxx            o                              ",
   "                     x   p    p     =      p    x         x         xxxxxxxx                          ",
   "                     xxxxxxxxxxxxxxxxxxxxxxxxxxxx         x!!!!!!!!!x                                 ",
   "                                                          xxxxxxxxxxx          xxxxxxx                ",
   "                                                                                     xpppp            ",
   "                                                                                     xxxxxxxx         ",
   "                                                                                                      ",
   "                                                                                                      ",
   "                                                                                                oo    ",
   "                                                                                               xxxx   ", 
   "                                                               xxxxx                                  ",
   "                                                                                                      ",
   "                               xx                       xxxxx               o                         ",
   "                                           oo                        xxxxxxxxxx     xxxxxxxxxxx       ",
   "                   xxxxxxxxx                                                  x!!!!!x                 ",
   "                o  x       x            xxxxxxxxxxx                           x!!!!!x                 ",
   "xx                 x       xppppppppppppx                                     xxxxxxx                 ",
   "x           pp  o  x       xxxxxxxxxxxxxx                                                             ",
   "x         xxxxxxxxxx                                                                                  ",
   "x @       x                                                                                           ",
   "xxxxxxxxxxx                                                                                           "],
 
 
 
  ["                                                                                                      ",
   "                                                                                                      ",
   "                                                                                                      ",
   "                                                                                                      ",
   "                                                                                                      ",
   "                             o    o                                                                   ",
   "                 xxx                 o                                                                ",
   "                 x       o             o                                                              ",
   "                 x                      o            pp                                               ",
   "                 xxxxxxx                xxxx         ppp                                              ",
   "                                           x!!xxxxxxxxxxxxxxxxxxxxxxxx                                ",
   "                                           xxxx                                   xxxxxxx             ",
   "                                                                        xxx         x                 ",
   "                                                                             o  o   x                 ",
   "                                          xxxxxx                             o  o   x                 ",
   "                                           v  v                              oppo   x                 ",
   "                                                                           xxxxxxxxx                  ",
   "                                                                           x                          ",
   "                                                                          xx                          ",
   "                                                                    o                                 ",
   "                                  o                                xxpp                               ",
   "                                 xxx                                                                  ",
   "                                 x x                       xx                                         ",
   "                         o       x x                     ppp                                          ",
   "                       xxxx      x x                                                                  ",
   "  xxx                  x  x      x x     o            o                                               ",
   "  x                    x  x      x x    xxx         xxxxx                                             ",
   "  x   @       pppp     x  x!!!!!!x x!!!!x x!!!!!x   x   x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x              ",
   "  xxxxxxxxxxxxxxxxxxxxxx  xxxxxxxx xxxxxx xxxxxxx   x   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx             ",
   "                                                x!!!x                                                 ",
   "                                                xxxxx                                                 "],
   
   ["                                                               ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "      x x                   x     x            x                ",
   "      x x                   x     x            x                ",
   "      xxx  xxx  x  x        x  x  x  x  xxxx   x                ",
   "       x   x x  x  x        x  x  x  x  x  x                    ",
   "       x   xxx  xxxx        xxxxxxx  x  x  x   x                ",
   "                                                                ",
   "                                                      xxx       ",
   "                                                        x       ",
   "   @                                               o    x       ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       ",
   "                                                                "]
 
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
