var GAME_LEVELS = [


  ["                                                                                            ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                  oo                         ",
   "                                                                                             ",
   "                                                   oo                                        ",
   "                                                   xx      xx                                ",
   "                                    o o      xx                                              ",
   "                                                               o                             ",
   "                                   xxxxx                       o                             ",
   "                                                              xxxxxxxxxxxx                   ",
   "  xx                                        o o               x          x            xx     ",
   "  x                           xxxxx         xxx               x          x             x     ",
   "  x            o                                           xxxx          x         o   x     ",
   "  x          xxxx       xxxx                               x             x         o   x     ",
   "  x  @       x  x                                          x             x         o   x     ",
   "  xxxxxxxxxxxx  xxxxxx                         xxxxxxxxxxxxx             x      xxxxxxxx     ",
   "                     x                         x                         x      x            ",
   "                     x!!!!!!!!!!!!!!!!!!!!!!!!!x                         x!!!!!!x            ",
   "                     x!!!!!!!!!!!!!!!!!!!!!!!!!x                         xxxxxxxx            ",
   "                     xxxxxxxxxxxxxxxxxxxxxxxxxxx                                             ",
   "                                                                                             ",
   "                                                                                             "],
   
   
   
  ["                                                                                                      ",
   "                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                           ",
   "                           v      v      v        v       x                                           ",
   "                                                          x                                           ",
   "                                                          x                                           ",
   "                                                          x                                           ",
   "                                                          x                                           ",
   "                                                          xxxxxxxxxxxxxxxxxxxxxxxxxxx                 ",
   "                                                                                                      ",
   "                                                                                               xx     ",
   "                                                                                                x     ",
   "                           o       o       o             o                      o          o    x     ",
   "                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     ",
   "            xxxx                                                                                      ",
   "       o                                                                                              ",
   "     xxxx                                                                                             ",
   "                                                                                                      ",
   "                                                                                                      ",
   "                                                               xx      o                              ",
   "        xxxxxxxxx                                                      o                              ",
   "                 xxxxx                          xxxxxxxxxxx            o                              ",
   "                     x                 =    o   x         x         xxxxxxxx                          ",
   "                     xxxxxxxxxxxxxxxxxxxxxxxxxxxx         x!!!!!!!!!x                                 ",
   "                                                          xxxxxxxxxxx          xxxxxxx                ",
   "                                                                                     x                ",
   "                                                                                     xxxxxxxx         ",
   "                                                                                                      ",
   "                                                                                                      ",
   "                                                                                                oo    ",
   "                                                                                               xxxx   ", 
   "                                                               xxxxx                                  ",
   "                                                                                                      ",
   "                               xx                       xxxxx               o                         ",
   "                                           oo                        xxxxxxxxxx     xxxxxxxxxxx       ",
   "                   xxxxxxxxx                                                  x!!!!!x                 ",
   "                o  x       x            xxxxxxxxxxx                           x!!!!!x                 ",
   "xx                 x       x!!!!!!!!!!!!x                                     xxxxxxx                 ",
   "x               o  x       xxxxxxxxxxxxxx                                                             ",
   "x         xxxxxxxxxx                                                                                  ",
   "x @       x                                                                                           ",
   "xxxxxxxxxxx                                                                                           "],
 
 
 
  ["                                                                                                      ",
   "                             o    o                                                                   ",
   "                 xxx                 o                                                                ",
   "                 x       o             o                                                              ",
   "                 x                      o                                                             ",
   "                 xxxxxxx                xxxx                                                          ",
   "                                           x!!xxxxxxxxxxxxxxxxxxxxxxxx                                ",
   "                                           xxxx                            xxx    xxx                 ",
   "                                                                                    x                 ",
   "                                                                             o  o   x                 ",
   "                                          xxxxxx                             o  o   x                 ",
   "                                           v  v                              o  o   x                 ",
   "                                                                           xxxxxxxxx                  ",
   "                                                                           x                          ",
   "                                                                          xx                          ",
   "                                                                    o                                 ",
   "                                  o                                xx                                 ",
   "                                 xxx                                                                  ",
   "                                 x x                         xx                                       ",
   "                         o       x x                                                                  ",
   "                       xxxx      x x                                                                  ",
   "  xxx                  x  x      x x     o               o                                            ",
   "  x                    x  x      x x    xxx            xxxxx                                          ",
   "  x   @                x  x!!!!!!x x !!!x x!!!!!!x     x   x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x           ",
   "  xxxxxxxxxxxxxxxxxxxxxx  xxxxxxxx xxxxx xxxxxxxx     x   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           ",
   "                                                   x!!!x                                              ",
   "                                                   xxxxx                                              "],
   
   ["                                                               ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "      x x                   x     x            x                ",
   "      x x                   x     x            x                ",
   "      xxx  xxx  x  x        x  x  x  x  xxxx   x                ",
   "       x   x x  x  x        x  x  x  x  x  x                    ",
   "       x   xxx  xxxx        xxxxxxx  x  x  x   x                ",
   "                                                                ",
   "                                                      xxx       ",
   "                                                        x       ",
   "   @                                               o    x       ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       ",
   "                                                                "]
 
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
